### PR TITLE
Add uninstall profile, modernize test-setup and cleanup travis builds

### PR DESCRIPTION
**Pull request by erral**

### CODE REVIEW

**Comment by gforcada** [comment]
Wow, creating not only the uninstall profile, but on top of that the whole test setup for it! :100: :+1: travis seems that is far from stable, so while I do not merge myself, I would say that if you feel confident enough with the changes, you could merge yourself :wink:

**Comment by erral** [comment]
I will check those failures, it looks like some buildout issues...

**Comment by erral** [comment]
Wow, and many flake8 issues :cry:

**Comment by erral** [comment]
At last everything is green! :sweat_smile:

**Comment by erral** [comment]
There are many changes after @gforcada's review, but if there's no opposition I'm merging this.

**Pull request merged**
