### PR TITLE
Fix i18n domain

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
@mauritsvanrees @gforcada can you review this, merge and make a new release, please?

**Comment by mauritsvanrees** [comment]
Why is this needed? What is wrong with `RedirectionTool` as domain? If it ain't broken, don't fix it. 

Also, I think for the xml files this would need an upgrade step: in some of these cases the domain is stored in the ZMI on an `i18n_domain` property.

**Comment by hvelarde** [comment]
@mauritsvanrees it was not working, now is; I can add an upgrade step.

`Products` namespace is needed; see: https://github.com/collective/Products.PloneKeywordManager/blob/master/Products/PloneKeywordManager/configure.zcml#L7

**Comment by mauritsvanrees** [comment]
No, the `Products` namespace is not needed; see https://github.com/collective/Products.Poi/blob/master/Products/Poi/configure.zcml#L5

When I use `Products.RedirectionTool` master, create a fresh Brazilian Portuguese Plone 5 site, install the redirection tool and go to `@@aliases-controlpanel` I can't read it, which is a good sign. ;-)

screen shot 2016-11-21 at 16 41 06

So why do you say it is not working? Are you having trouble with the master buildout of this repository? Or with a custom buildout?
Do you only have trouble with some translations and not with all? Are the `.mo` files being generated or are you maybe missing `zope_i18n_compile_mo_files true` in your instance environment?

**Comment by hvelarde** [comment]
thanks! then what is missing from here are the .mo file on the egg; a new release will be needed anyway.

**Comment by mauritsvanrees** [comment]
I have released 1.4.1.

**Pull request closed without merging**
